### ISSUE TITLE
1.9.18 release todo

### ISSUE THREAD

**Issue by gdevenyi** [BIC-MNI/minc-toolkit-v2#104]
I want to make 1.9.18 release soon, so here I'm going to track outstanding issues/bugs I want to fix beforehand:
- [x] https://github.com/InsightSoftwareConsortium/ITK/pull/1831
- [x] https://github.com/BIC-MNI/minc-toolkit-v2/issues/45
- [x] https://github.com/BIC-MNI/minc-toolkit-v2/issues/103
- [x] https://github.com/BIC-MNI/minc-toolkit-v2/issues/102
- [ ] https://github.com/BIC-MNI/minc-toolkit-v2/issues/87
- [x] https://github.com/BIC-MNI/minc-toolkit-v2/issues/72
- [x] https://github.com/BIC-MNI/minc-toolkit-v2/issues/83
- [x] https://github.com/BIC-MNI/minc-toolkit-v2/issues/7
- [x] https://github.com/BIC-MNI/BEaST/issues/6
- [x] update conglomerate commit hash

**Comment by gdevenyi** [comment]
Everything I really wanted to fix in the release is ready except C3D is broken: https://github.com/vfonov/Convert3D/issues/1

@vfonov any thoughts?
would you like anything else added to the release? Some of the other superbuild packages have had commits which could be bumped as well I suspect.

**Comment by vfonov** [comment]
time to make a new official release of libminc ?

**Comment by gdevenyi** [comment]
Yes, we should probably address at least https://github.com/BIC-MNI/libminc/issues/108

Do you have any wishlist issues you'd like to address in any packages first?

**Comment by gdevenyi** [comment]
@vfonov anything else you'd like to do before release? I have changes to push for build_packages

**Comment by vfonov** [comment]
let's try to make  a release as it is

**Comment by gdevenyi** [comment]
k, I need to clear some space here so I can buildpackages for all the new targets

**Comment by vfonov** [comment]
I found some problems in MacOS build, more changes are coming
